import { pgTable, uuid, text, integer, bigint, boolean, date, timestamp, index, check } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { matchmakers } from './matchmakers';

export const customers = pgTable('customers', {
  id: uuid('id').defaultRandom().primaryKey(),
  matchmakerId: uuid('matchmaker_id').notNull().references(() => matchmakers.id, { onDelete: 'cascade' }),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  gender: text('gender').notNull(),
  dateOfBirth: date('date_of_birth').notNull(),
  profilePhotoUrl: text('profile_photo_url'),
  email: text('email'),
  phoneNumber: text('phone_number'),
  country: text('country').default('India'),
  city: text('city').notNull(),
  heightCm: integer('height_cm'),
  weightKg: integer('weight_kg'),
  undergradCollege: text('undergrad_college'),
  degree: text('degree'),
  postgradCollege: text('postgrad_college'),
  postgradDegree: text('postgrad_degree'),
  currentCompany: text('current_company'),
  designation: text('designation'),
  annualIncomeInr: bigint('annual_income_inr', { mode: 'number' }),
  incomeTier: text('income_tier'),
  maritalStatus: text('marital_status'),
  siblings: integer('siblings').default(0),
  caste: text('caste'),
  subCaste: text('sub_caste'),
  religion: text('religion'),
  motherTongue: text('mother_tongue'),
  gotra: text('gotra'),
  manglik: text('manglik'),
  horoscopeRequired: boolean('horoscope_required').default(false),
  diet: text('diet'),
  drinking: text('drinking'),
  smoking: text('smoking'),
  familyType: text('family_type'),
  familyValues: text('family_values'),
  languagesKnown: text('languages_known').array(),
  wantKids: text('want_kids'),
  openToRelocate: text('open_to_relocate'),
  openToPets: text('open_to_pets'),
  willingToSettleAbroad: boolean('willing_to_settle_abroad').default(false),
  preferredAgeMin: integer('preferred_age_min'),
  preferredAgeMax: integer('preferred_age_max'),
  preferredHeightMin: integer('preferred_height_min'),
  preferredReligion: text('preferred_religion').array(),
  preferredCaste: text('preferred_caste').array(),
  preferredCity: text('preferred_city').array(),
  journeyStage: text('journey_stage').default('onboarding').notNull(),
  aboutMe: text('about_me'),
  physicallyChallenged: boolean('physically_challenged').default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => ({
  matchmakerIdIdx: index('idx_customers_matchmaker_id').on(table.matchmakerId),
  matchmakerGenderIdx: index('idx_customers_matchmaker_gender').on(table.matchmakerId, table.gender),
  matchmakerStageIdx: index('idx_customers_matchmaker_stage').on(table.matchmakerId, table.journeyStage),
  genderCheck: check('gender_check', sql`${table.gender} in ('male', 'female', 'other')`),
  incomeTierCheck: check('income_tier_check', sql`${table.incomeTier} in ('below_5l','5l_10l','10l_20l','20l_50l','50l_plus')`),
  maritalStatusCheck: check('marital_status_check', sql`${table.maritalStatus} in ('never_married','divorced','widowed','separated')`),
  manglikCheck: check('manglik_check', sql`${table.manglik} in ('yes','no','anshik','dont_matter')`),
  dietCheck: check('diet_check', sql`${table.diet} in ('vegetarian','non_vegetarian','eggetarian','jain','vegan')`),
  drinkingCheck: check('drinking_check', sql`${table.drinking} in ('never','occasionally','yes')`),
  smokingCheck: check('smoking_check', sql`${table.smoking} in ('never','occasionally','yes')`),
  familyTypeCheck: check('family_type_check', sql`${table.familyType} in ('nuclear','joint','extended')`),
  familyValuesCheck: check('family_values_check', sql`${table.familyValues} in ('traditional','moderate','liberal')`),
  wantKidsCheck: check('want_kids_check', sql`${table.wantKids} in ('yes','no','maybe')`),
  openToRelocateCheck: check('open_to_relocate_check', sql`${table.openToRelocate} in ('yes','no','maybe')`),
  openToPetsCheck: check('open_to_pets_check', sql`${table.openToPets} in ('yes','no','maybe')`),
  journeyStageCheck: check('journey_stage_check', sql`${table.journeyStage} in ('onboarding','active','match_sent','matched','closed','paused')`),
}));
