import { pgTable, uuid, text, integer, bigint, boolean, date, timestamp, index, check } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

export const poolProfiles = pgTable('pool_profiles', {
  id: uuid('id').defaultRandom().primaryKey(),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  gender: text('gender').notNull(),
  dateOfBirth: date('date_of_birth').notNull(),
  profilePhotoUrl: text('profile_photo_url'),
  email: text('email'),
  phoneNumber: text('phone_number'),
  country: text('country').default('India'),
  city: text('city').notNull(),
  heightCm: integer('height_cm'),
  weightKg: integer('weight_kg'),
  undergradCollege: text('undergrad_college'),
  degree: text('degree'),
  currentCompany: text('current_company'),
  designation: text('designation'),
  annualIncomeInr: bigint('annual_income_inr', { mode: 'number' }),
  incomeTier: text('income_tier'),
  maritalStatus: text('marital_status'),
  siblings: integer('siblings').default(0),
  caste: text('caste'),
  subCaste: text('sub_caste'),
  religion: text('religion'),
  motherTongue: text('mother_tongue'),
  gotra: text('gotra'),
  manglik: text('manglik'),
  horoscopeRequired: boolean('horoscope_required').default(false),
  diet: text('diet'),
  drinking: text('drinking'),
  smoking: text('smoking'),
  familyType: text('family_type'),
  familyValues: text('family_values'),
  languagesKnown: text('languages_known').array(),
  wantKids: text('want_kids'),
  openToRelocate: text('open_to_relocate'),
  openToPets: text('open_to_pets'),
  aboutMe: text('about_me'),
  physicallyChallenged: boolean('physically_challenged').default(false),
  isActive: boolean('is_active').default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (table) => ({
  genderIdx: index('idx_pool_gender').on(table.gender),
  activeIdx: index('idx_pool_active').on(table.isActive).where(sql`is_active = TRUE`),
  genderActiveIdx: index('idx_pool_gender_active').on(table.gender).where(sql`is_active = TRUE`),
  genderCheck: check('gender_check', sql`${table.gender} in ('male', 'female', 'other')`),
}));
